# Generated by Django 3.0.6 on 2020-07-03 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bill', models.ImageField(upload_to='')),
                ('remarks', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Not Reviewed', 'Not Reviewed'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Not Reviewed', max_length=20)),
                ('comments', models.CharField(default='-', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
