# Generated by Django 3.0.6 on 2020-07-04 16:45

import Reimbursements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reimbursements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill',
            field=models.ImageField(null=True, upload_to=Reimbursements.models.path_and_rename),
        ),
    ]
