# Generated by Django 3.0.6 on 2020-07-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reimbursements', '0003_auto_20200726_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
