# Generated by Django 3.0.6 on 2020-07-21 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mentor', models.CharField(max_length=100)),
                ('member1', models.CharField(max_length=100)),
                ('regno1', models.CharField(max_length=9)),
                ('member2', models.CharField(max_length=100, null=True)),
                ('regno2', models.CharField(max_length=9, null=True)),
                ('member3', models.CharField(max_length=100, null=True)),
                ('regno3', models.CharField(max_length=9, null=True)),
                ('member4', models.CharField(max_length=100, null=True)),
                ('regno4', models.CharField(max_length=9, null=True)),
                ('member5', models.CharField(max_length=100, null=True)),
                ('regno5', models.CharField(max_length=9, null=True)),
                ('member6', models.CharField(max_length=100, null=True)),
                ('regno6', models.CharField(max_length=9, null=True)),
            ],
        ),
    ]
