# Generated by Django 3.0.6 on 2020-07-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20200722_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='regno1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='regno2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='regno3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='regno4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='regno5',
        ),
        migrations.RemoveField(
            model_name='project',
            name='regno6',
        ),
    ]
