# Generated by Django 3.0.6 on 2020-06-19 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(choices=[('MAL', 'Male'), ('FEM', 'Female'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('room', models.CharField(max_length=10)),
                ('block', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
