# Generated by Django 3.0.6 on 2020-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0004_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='owner',
        ),
        migrations.AddField(
            model_name='attendance',
            name='isPresent',
            field=models.BooleanField(default=False),
        ),
    ]
