# Generated by Django 3.0.6 on 2020-07-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0005_auto_20200713_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='meeting',
            field=models.CharField(max_length=100),
        ),
    ]
