# Generated by Django 3.0.6 on 2020-06-25 15:22

import Members.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersListFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('csv', models.FileField(upload_to=Members.models.path_and_rename)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
