# Generated by Django 3.0.8 on 2021-01-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='fcm',
            field=models.TextField(null=True),
        ),
    ]
